In [1]:
import numpy as np
import time
import matplotlib.pyplot as plt

# Define matrix size
n = 3
A = np.random.rand(n, n)
B = np.random.rand(n, n)

# (a) NumPy's built-in operator
print("(a)")
C = A @ B  # NumPy's matrix multiplication operator
print(C)

# (b) Using three nested for loops
print("(b)")
C1 = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C1[i, j] += A[i, k] * B[k, j]
print(C1)
diff = C - C1
maxdiff = np.max(np.abs(diff))
print("Max difference:", maxdiff)

# (c) Swapping the two outer loops (j, i)
print("(c)")
C1 = np.zeros((n, n))
for j in range(n):
    for i in range(n):
        for k in range(n):
            C1[i, j] += A[i, k] * B[k, j]
print(C1)
maxdiff = np.max(np.abs(C - C1))
print("Max difference:", maxdiff)

# (d) Using two loops and sum()
print("(d)")
C1 = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        C1[i, j] = np.sum(A[i, :] * B[:, j])
print(C1)
maxdiff = np.max(np.abs(C - C1))
print("Max difference:", maxdiff)

# (e) Transposing A
print("(e)")
AT = A.T
C1 = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        C1[i, j] = np.sum(AT[:, i] * B[:, j])
print(C1)
maxdiff = np.max(np.abs(C - C1))
print("Max difference:", maxdiff)

# (f) Transposing B
print("(f)")
BT = B.T
C1 = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        C1[i, j] = np.sum(A[i, :] * BT[j, :])
print(C1)
maxdiff = np.max(np.abs(C - C1))
print("Max difference:", maxdiff)

# (g) Matrix multiplication with increasing size
print("(g)")
for n in [10, 100, 1000]:
    print(f"Matrix size: {n}")
    A = np.random.rand(n, n)
    B = np.random.rand(n, n)

    # (a) Built-in multiplication
    start = time.time()
    C = A @ B
    end = time.time()
    print("Built-in operator time:", end - start)

    # (b) Three nested loops
    start = time.time()
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    end = time.time()
    print("Triple loop time:", end - start)

    # (c) Swapping outer loops
    start = time.time()
    C = np.zeros((n, n))
    for j in range(n):
        for i in range(n):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    end = time.time()
    print("Swapped loop time:", end - start)

    # (d) Two loops with sum()
    start = time.time()
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            C[i, j] = np.sum(A[i, :] * B[:, j])
    end = time.time()
    print("Two loops with sum time:", end - start)

    # (e) Transposing A
    start = time.time()
    AT = A.T
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            C[i, j] = np.sum(AT[:, i] * B[:, j])
    end = time.time()
    print("Transposed A time:", end - start)

    # (f) Transposing B
    start = time.time()
    BT = B.T
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            C[i, j] = np.sum(A[i, :] * BT[j, :])
    end = time.time()
    print("Transposed B time:", end - start)

# (g) Scaling study for matrix multiplication
nvec = [10, 20, 50, 100, 200, 500, 1000]
CPUt1 = []
CPUt2 = []
CPUt3 = []

for n in nvec:
    A = np.random.rand(n, n)
    B = np.random.rand(n, n)

    # Built-in multiplication
    start = time.time()
    C = A @ B
    end = time.time()
    CPUt1.append(end - start)

    # Triple loop (only for small matrices)
    if n <= 1000:
        start = time.time()
        C = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                for k in range(n):
                    C[i, j] += A[i, k] * B[k, j]
        end = time.time()
        CPUt2.append(end - start)

        # Two loops with transposed A
        start = time.time()
        AT = A.T
        C = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                C[i, j] = np.sum(AT[:, i] * B[:, j])
        end = time.time()
        CPUt3.append(end - start)

# Plot CPU time scaling
plt.figure()
plt.loglog(nvec, CPUt1, 'bo-', label="Built-in")
plt.loglog(nvec[:len(CPUt2)], CPUt2, 'ro-', label="Triple loop")
plt.loglog(nvec[:len(CPUt3)], CPUt3, 'go-', label="Two loops with sum")
plt.xlabel('Matrix size (n)')
plt.ylabel('CPU time (s)')
plt.legend()
plt.title('CPU Time Scaling for Matrix Multiplication')
plt.savefig('matmul_scaling.png')
plt.show()

(a)
[[0.32057922 0.70392346 0.3565454 ]
 [0.50814578 0.87616687 0.85448546]
 [0.47959019 0.68200745 0.90892313]]
(b)
[[0.32057922 0.70392346 0.3565454 ]
 [0.50814578 0.87616687 0.85448546]
 [0.47959019 0.68200745 0.90892313]]
Max difference: 5.551115123125783e-17
(c)
[[0.32057922 0.70392346 0.3565454 ]
 [0.50814578 0.87616687 0.85448546]
 [0.47959019 0.68200745 0.90892313]]
Max difference: 5.551115123125783e-17
(d)
[[0.32057922 0.70392346 0.3565454 ]
 [0.50814578 0.87616687 0.85448546]
 [0.47959019 0.68200745 0.90892313]]
Max difference: 5.551115123125783e-17
(e)
[[0.32057922 0.70392346 0.3565454 ]
 [0.50814578 0.87616687 0.85448546]
 [0.47959019 0.68200745 0.90892313]]
Max difference: 5.551115123125783e-17
(f)
[[0.32057922 0.70392346 0.3565454 ]
 [0.50814578 0.87616687 0.85448546]
 [0.47959019 0.68200745 0.90892313]]
Max difference: 5.551115123125783e-17
(g)
Matrix size: 10
Built-in operator time: 5.7220458984375e-06
Triple loop time: 0.00047397613525390625
Swapped loop time: 0.000473

KeyboardInterrupt: 